### ISSUE TITLE
Add Scala 3 support for uPickle and Circe

### ISSUE THREAD

**Issue by luksow** [pjfanning/pekko-http-json#1]
Seems that simply https://github.com/hseeberger/akka-http-json/pull/757 could be cherry-picked (as noted in https://github.com/hseeberger/akka-http-json/issues/755).

**Comment by pjfanning** [comment]
I only just saw this - added #2

**Comment by pjfanning** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/pjfanning/pekko-http-circe_3/1.40.0-RC3_17-0a23ccd2-SNAPSHOT/ is published - likewise upickle equivalent
