### ISSUE TITLE
Exception: java.lang.AbstractMethodError thrown from the UncaughtExceptionHandler in thread "main"

### ISSUE THREAD

**Issue by KevinAtSesam** [pjfanning/pekko-http-json#25]
Upgrading from 2.5.0 to 2.6.0 gives us a AbstractMethodError. 

## Background

> Exception in thread "main" java.lang.AbstractMethodError: Receiver class com.sesamsolutions.application.Main$ does not define or inherit an implementation of the resolved method 'abstract void com$github$pjfanning$pekkohttpcirce$BaseCirceSupport$_setter_$com$github$pjfanning$pekkohttpcirce$BaseCirceSupport$$defaultMediaTypes_$eq(scala.collection.immutable.Seq)' of interface com.github.pjfanning.pekkohttpcirce.BaseCirceSupport.

This happens with 
- Circe  0.14.7
- OpenJDK 21.0.3
- Pekko 1.0.2

**Comment by pjfanning** [comment]
You may need to recompile your code. This lib currently does not guarantee 100% binary compatibility across major or minor releases. With patch releases, I try to keep changes to a minimum.

At some stage, I may have time to add MiMa checking.

**Comment by KevinAtSesam** [comment]
> You may need to recompile your code. This lib currently does not guarantee 100% binary compatibility across major or minor releases. 

That might explain the issue. I've cleared all caches on my machine and our build server, and everything compiles and tests correctly. Sorry for wasting your time, but thanks for your support none the less.
